name: CI Pipeline
run-name: CI Test
on: [push]
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: sign aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}

#      - name: Run CD for Stagin
#        run: |
#          # TODO Perform deployment steps for the staging environment

#  lint:
#    runs-on: ubuntu-latest
#    steps:
#            - name: Checkout the cod
#              uses: actions/checkout@v2
#
#            - name: Set up JDK 17
#              uses: actions/setup-java@v2
#              with:
#                java-version: '17'
#                distribution: 'adopt'
#
#            - name: Run Lint
#              run: ./gradlew lint
#
#            - name: Upload html test report
#              uses: actions/upload-artifact@v2
#              with:
#                name: index.html
#                path: app/build/reports/lint-results-debug.html
#
#  unit-test:
#    needs: [lint]
#    runs-on: ubuntu-latest
#    steps:
#            - name: Checkout the code
#              uses: actions/checkout@v2
#
#            - name: Set up JDK 17
#              uses: actions/setup-java@v2
#              with:
#                java-version: '17'
#                distribution: 'adopt'
#
#            - name: Run tests
#              run: ./gradlew test
#
#            - name: Upload test report
#              uses: actions/upload-artifact@v2
#              with:
#                name: unit_test-report
#                path: app/build/reports/tests/testDebugUnitTest/


